# Generated by Django 3.0.6 on 2020-08-16 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('total_match', models.IntegerField()),
                ('total_wins', models.IntegerField()),
                ('total_loss', models.IntegerField()),
                ('total_draw', models.IntegerField()),
                ('total_goal_scored', models.IntegerField()),
                ('total_goal_conceded', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GS_by_1', models.IntegerField()),
                ('GS_by_2', models.IntegerField()),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='pes.Player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='pes.Player')),
            ],
        ),
    ]
