# Generated by Django 3.0.6 on 2020-08-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
