# Generated by Django 3.0.6 on 2020-08-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pes', '0002_player_total_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='total_goal_diff',
            field=models.IntegerField(default=0),
        ),
    ]
