# Generated by Django 3.1 on 2020-09-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pes', '0003_player_total_goal_diff'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='manager',
            field=models.CharField(default='unknown', max_length=30),
        ),
    ]
