# Generated by Django 3.1 on 2020-09-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pes', '0004_player_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='logo',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='pictures'),
        ),
    ]
