# Generated by Django 3.1 on 2020-09-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pes', '0005_player_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='abbr',
            field=models.CharField(default='FCB', max_length=4),
        ),
    ]
